<ul class="accordion">
  <li class="entry opened">
    <h3>Radbörse</h3>
    <div class="details">
      <p>Sie findet jährlich im Radhaus Kastner in Kuppenheim statt.</p>
      <ol>
        <li>
          <h4>2009</h4>
          <a href="#">Auch die 19. Radbörse war ein Riesenerfolg</a>
          <p>Zur 19. Radbörse kamen leider keine Besucher. Glücklicherweise
            haben trotzdem alle Besucher gespendet. <a href="#">mehr...</a></p>
        </li>
        <li>
          <h4>2008</h4>
          <a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</a>
        </li>
        <li>
          <h4>2006</h4><strong></strong>
        </li>
        <li>
          <h4>2004</h4><strong></strong>
        </li>
        <li>
          <h4>2003</h4><strong></strong>
        </li>
        </ol>
    </div>
  </li>
  <li class="entry">
    <h3>Konzerte</h3>
    <div class="details">
      <p>Lalelu</p>
    </div>
  </li>
  <li class="entry">
    <h3>Kinderfest</h3>
    <div class="details">
      <p>Das Highlight des Kinderfestes ist die Hüpfburg.</p>
    </div>
  </li>
  <li class="entry">
    <h3>Basar</h3>
    <div class="details">
      <p>Beim Basar wurden viele tolle Sachen verkauft.</p>
    </div>
  </li>
</ul>
