<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<ul class="accordion">
  <li class="entry opened">
    <h3>Radbörse</h3>
    <div class="details">
      <p>Sie findet jährlich im Frühjahr im Radhaus Kastner in Kuppenheim statt. Als Tauschbörse rund ums Rad ist sie inzwischen ein fester Bestandteil unserer Aktivitäten in Kuppenheim. Sie wird von der Bevölkerung gerne genutzt, um gut gerüstet und sattelfest die ersten warmen Sonnenstrahlen während eines Radausflugs zu genießen.</p>
      <ol>
        <li>
          <h4>2009</h4>
          <a href="#">Auch die 19. Radbörse war ein Riesenerfolg</a>
          <p>Zur 19. Radbörse kamen leider keine Besucher. Glücklicherweise
            haben trotzdem alle Besucher gespendet. <a href="#">mehr...</a></p>
        </li>
        <li>
          <h4>2008</h4>
          <a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörse</a>
        </li>
        <li>
          <h4>2006</h4>
          <a href="#">2006 Euro Erlös bei 17. Kuppenheimer Fahrradbörse</a>
        </li>
        <li>
          <h4>2004</h4>
          <a href="#">Erneut Rekordsumme bei Fahrradbörse: 2213 Euro</a>
        </li>
        <li>
          <h4>2003</h4>
          <a href="">Bisher höchster Erlös bei Radbörse mit 1854 Euro Erlös</a>
        </li>
      </ol>
    </div>
  </li>
  <li class="entry">
    <h3>Konzerte</h3>
    <div class="details">
      <p>Seit 2004 können wir für unsere Konzerte das Foyer des Neuen Rathauses in Kuppenheim nutzen. Im Gegensatz zu den früheren "Favorite-Konzerten" (beim Schloß Favorite nahe Rastatt) plagen uns dadurch keine Sorgen mehr mit dem Wettergott - im Gegenteil steht uns bei schönem Wetter zusätzlich der Vorplatz für "OpenAir"-Feeling zur Verfügung. Die hervorragende Resonanz auf unsere bisherigen Veranstaltungen im Neuen Rathaus zeigt, daß dieses neue Ambiente guten Anklang bei Künstlern und Zuhörern findet. Eine Übersicht über unsere "Rathaus-Konzerte" folgt in Kürze!</p>
      <ol>
        <li>
          <h4>2003</h4>
          <a href="#"></a>
          <p>25 Jahre terre des hommes Murgtal / Mittelbaden: Das musste mit einem Benefiz-Serenaden-Konzert im Schloss Favorite gefeiert werden. Es war das zehnte seiner Art, aber das erste mit dem Quantz-Collegium. <a href="#">mehr...</a></p>
        </li>
        <li>
          <h4>2002</h4>
          <a href="#"></a>
          <p>Am 14. Juli 2002 war es wieder soweit. Unsere Arbeitsgruppe lud zum 9. Open-Air-Konzert beim Schloss Favorite ein. Trotz ungünstiger Witterung kamen ca. 150 Besucher, um sich musikalisch unterhalten zu lassen. <a href="#">mehr...</a></p>
        </li>
        <li>
          <h4>2001</h4>
          <a href="#"></a>
          <p>Im Jahr 2001 haben wir aufgrund der Terroranschläge vom 11. September das Favorite-Konzert kurzfristig angesagt. Stattdessen wurde eine kleine Gedenkveranstaltung mit musikalischer Umrahmung beim Schloss Favorite durchgeführt. Das Ersatzkonzert fand dann im Oktober in der Markthalle Bischweier statt. Gäste bei diesem Benefizkonzert waren "brass and fun", die Bigband der Stadt Bühl. <a href="#">mehr...</a></p>
        </li>
      </ol>
    </div>
  </li>
  <li class="entry">
    <h3>Kinderfest</h3>
    <div class="details">
      <p>Für viele Familien eine äußerst beliebte Veranstaltung, die meistens am ersten Wochenende nach den Sommerferien auf dem Gelände der Kuppenheimer Realschule stattfindet. Ponyreiten, Kistenstapeln, Schminkecke, Spielparcour, Kindertheater, Zauberer... die Kleinen fühlen sich an diesem Nachmittag bei uns pudelwohl. Ähnlich geht es den Eltern, denn sie können sich gemütlich mit Freunden und Bekannten unterhalten und wissen ihre Kleinen unter zuverlässiger Aufsicht. Eine entsprechende Auswahl an Getränken und Speisen, und da ist selbstverständlich auch immer etwas speziell für Kinder dabei, lässt Hunger oder Durst gleich gar nicht aufkommen. So verbringen alle 2 Jahre um die 2500 Besucher einen Nachmittag, bei dem Spiel, Spaß, Sport und Unterhaltung für Kinder im Mittelpunkt stehen.</p>
    </div>
  </li>
  <li class="entry">
    <h3>Basar</h3>
    <div class="details">
      <p>Jedes zweite Jahr ist die Wörtelhalle in Kuppenheim gut gefüllt, wenn unsere Gruppe ein breitgefächertes Angebot aus den Bereichen Umweltschutz, Kunsthandwerk und Holzwaren präsentiert. Märchenlesungen und Basteln, Töpfern und Vieles mehr ist für die Kinder angesagt. Außerdem laden ausgezeichnetes Mittagessen, eine lange Kuchentheke und Waffeln zu längerem Verweilen ein.</p>
    </div>
  </li>
</ul>
