<div class="maincontent">
  <h2>Unsere Aktivitäten</h2>
  <p>Es ist das Ziel von terre des hommes Murgtal, die Bevölkerung über die Probleme der Kinder und Familien in der "Dritten Welt" aufzuklären, und über wirtschaftliche und politische Ursachen und Zusammenhänge zu informieren.
  So haben wir in den vergangenen Jahren Aktionen und Aktivitäten genutzt, um über Kinderarbeit (RUGMARK-Initiative/Blumenkampagne), Landminen, Strassenkinder, Kinder und Bildung, Kinderrechte allgemein, Kindersoldaten, sexuelle Ausbeutung von Kindern und Kinderhandel zu informieren.
  Außer den regelmäßigen Aktionen wie der <a href="#entry1">Radbörse</a>, verschiedenen <a href="#entry2">Konzerten</a> sowie dem traditionellen <a href="#entry3">Kinderfest</a> und dem <a href="#entry4">Basar</a> organisieren wir auch Kunstausstellungen, Verkaufs-und Infostände und Märchenlesungen und beteiligen uns an Spendenaktionen im Rahmen der Katastrophenhilfe z. B. bei der Tsunami-Katastrophe (Südasien), Erdbeben (Nicaragua), Überschwemmungen (Mozambik), der Aufbauhilfe in Afghanistan etc.</p>
</div>
