<div class="donation-button-1">
    <a href="#">
        <img src="images/info-icon.png"/>            <p>Unser Spendenkonto</p>
        <p>Unser Spendenkonto</p>
    </a>
</div>
        
    




<div class="donation-button-2">
        <a href="#">
            
            <div class="white-box">
                <img src="images/spenden-icon.png">
                <p>sicher & schnell 
                    <span>online spenden</span>
                </p>
            </div>
        </a>
</div>