<!-- JG: Bitte zwei separate Dateien daraus machen, wie anfangs richtig geamcht. Dann schauen, ob es übereinstimmende Regeln gibt, die zu einer Gesamt-Klasse zusammengefasst werden können.  -->

<div class="donation-button-1">
    <a href="#">
        <img src="images/info-icon.png"/>
        <!-- JG:
          - Warum doppelter Absatz?
          - Warum überhaupt ein Absatz? Ein Span würde reichen. Sie benötigen keinen Absatz um das Element und es handelt sich nicht um einen vollständigen Satz.  -->
        <!-- <p>Unser Spendenkonto</p> -->
        <p>Unser Spendenkonto</p>
    </a>
</div>






<div class="donation-button-2">
        <a href="#">

            <div class="white-box">
                <img src="images/spenden-icon.png">
                <!-- JG:
                    - Absatz ist hier die falsche Wahl, s.o.
                    - Das &-Zeihen muss maskiert werden, deshalb wird es von Ihrem Editor bestimmt markiert. Es sollte als &amp;  eingebunden werden. -->
                <p>sicher & schnell
                    <span>online spenden</span>
                </p>
            </div>
        </a>
</div>
