<div class="main-content">

    <h3> Helfen Sie mit!</h3>
    
    <img src="images/grosses-contentbild.jpg">
    <p>
        Keine Angst vor Engagement - so könnte das Motto zur Mitarbeit in unserer Gruppe lauten, denn jeder Mitarbeiter und Helfer ist bei uns willkommen und geschätzt. Jeder bestimmt selbst Umfang und Ausmaß seiner Unterstützung. Unterstützung benötigen wir bei vielen Aktivitäten. Hier nur eine kleine Auswahl an Möglichkeiten:
    </p>
    <ul>
        <li>Flyer verteilen / Plakate aufhängen</li>
        <li>Sponsoren suchen/aktivieren</li>
        <li>im Freundes- und Bekanntenkreis werben</li>
        <li>usw.</li>
    </ul>
    
    <h3>Auch Ihre Spenden helfen</h3>
    
    <p>
        Wollen sie nicht direkt bei uns mitarbeiten, können Sie uns Natürlich auch finanziell unterstützen. Beispielsweise anlässlich eines persönlichen Ereignisses durch Spenden bei
    </p>
    <ul>
        <li>runden Geburtstagen</li>
        <li>Geburten</li>
        <li>usw.</li>
    </ul>
    
</div>