    <div class="kontakt">

        <div class="kontakt_head">
            <h3>Kontakt mit terre des hommes Murgtal</h3>
            <p>Schreiben Sie uns eine Nachricht - wir melden uns so schnell wie möglich bei Ihnen</p>
        </div>
        <form class="formular clearfix">

            <div class="line clearfix">
                <label for="form_select">
                    <h4>Was ist Ihr Anliegen?</h4>
                    <p>Wählen Sie bitte aus, worum es Ihnen geht - so finden wir schneller den richtigen Ansprechpartner</p>

                </label>
                <select id="form_select" class="form" name="form_select">
                    <option>Allgemeines</option>
                    <option>Rechnung</option>
                    <option>Auftrag</option>
                </select>
            </div>

            <div class="line clearfix">
                <label for="name">
                    <h4>Ihr Name*</h4>
                </label>
                <input class="form" id="name" name="name" placeholder="Ihr Name">
            </div>

            <div class="line clearfix">
                <label for="email">
                    <h4>Ihre E-Mail Adresse*</h4>
                </label>
                <input class="form" id="email" name="email" placeholder="Ihre E-Mail Adresse">
            </div>

            <div class="line clearfix">
                <label for="message">
                    <h4>Ihre Nachricht*</h4>
                    <p>Hinterlassen Sie hier auch ihre Adresse oder Telefonnummer, wenn Sie möchten, dass wir telefonisch oder schriftlich mit Ihnen in Kontakt treten.</p>
                </label>
                <textarea id="message" name="message" placeholder="Ihre Nachricht an tdh Murgtal"></textarea>
            </div>
            <div class="button">
                <button type="button">Nachricht senden</button>
            </div>
        </form>
    </div>
