<div class=main-content>
  <h2>Presse</h2>
  <p><strong>Für unsere Arbeit ist es wichtig, dass darüber geredet wird, was wir tun - nur so erfahren die Menschen, wie sie mit ihren Spenden Kindern eine Zukunft geben können.</strong></p>
  <p>Wir hoffen daher, dass sie auf unseren Seiten alles finden, was sie brauchen um über uns zu berichten. Einen Überblick über unsere Aktionen finden Sie, chronologisch sortiert, im Bereich <a href="ueberuns-aktivitaeten.php">Aktivitäten</a></p>
  <p>Wer wir sind und was die Philosophie unseres Handelns ist, finden sie unter <a href"ueberuns-dasteam.php">Über Uns</a>. Sollten Sie weitere Fragen haben, zögern Sie nicht, uns anzusprechen.</a></p>
</div class=main-content>
