<div class="content-widget">
  <h3>Vorgestellt</h3>
  <h4>Franz Bürk - "Der Feuermacher"</h4>
  <img src="images/fackelmann.jpg">
  <p>Franz Bürk aus Achern - "der Feuermacher" - war eine grosse Bereicherung für das Kinderfest 2001, indem er Jung und Alt eindrucksvoll demonstrierte, wie man ohne technische Hilfsmittel Feuer entzünden kann.</p>
  <a href="meldungen.php">Mehr in den Meldungen</a>
</div>
