<div class="table-employee-wrapper">

  <div>
    Hier finden sie eine Liste all unserer aktiven Mitarbeiter.
  </div>
  <div>
    Mit der Karte können sie feststellen, wer von uns wo aktiv ist.
  </div>

  <table class="emptable tablesorter">
    <thead class="headrow">
      <th>
        Name
      </th>
      <th>
        Telefon
      </th>
      <th>
        Ort
      </th>
    </thead>
    <tbody>
      <tr class="contentrow">
        <td class="namecol">
          Alonso, Martin
        </td>
        <td>
          01234/223344
        </td>
        <td>
          Mainz
        </td>
      </tr>

      <tr class="contentrow">
        <td class="namecol">
          Müller, Martin
        </td>
        <td>
          01234/223344
        </td>
        <td>
          Frankfurt
        </td>
      </tr>

      <tr class="contentrow">
        <td class="namecol">
          Frank, Wolfgang
        </td>
        <td>
          02176/770505
        </td>
        <td>
          Mainz
        </td>
      </tr>
    </tbody>
  </table>
</div>
