<!-- Custom-Table-Sorter for Table-Sponsor -->
    <div class="underlined-table-row ">
        <div class="table-head-style1">
            <p>
                <strong>Was wollen Sie sehen?</strong>
            </p>
            <div>
                <select name="" class="select-field horizontal-list-item sort-attr1">
                    <option value="A">A</option>
                    <option value="Ä">Ä</option>
                    <option value="B">B</option>
                    <option value="C">C</option>
                    <option value="D">D</option>
                    <option value="E">E</option>
                    <option value="F">F</option>
                    <option value="G">G</option>
                    <option value="H">H</option>
                    <option value="I">I</option>
                    <option value="J">J</option>
                    <option value="K">K</option>
                    <option value="L">L</option>
                    <option value="M">M</option>
                    <option value="N">N</option>
                    <option value="O">O</option>
                    <option value="Ö">Ö</option>
                    <option value="P">P</option>
                    <option value="Q">Q</option>
                    <option value="R">R</option>
                    <option value="S">S</option>
                    <option value="T">T</option>
                    <option value="U">U</option>
                    <option value="Ü">Ü</option>
                    <option value="V">V</option>
                    <option value="W">W</option>
                    <option value="X">X</option>
                    <option value="Y">Y</option>
                    <option value="Z">Z</option>
                </select>
                <select name="" class="select-field horizontal-list-item sort-attr2">
                    <option value="0">Sponsor</option>
                    <option value="1">Ort</option>
                </select>
                <div class="horizontal-list-item">
                    <p class="">
                        Auswahl treffen und dann
                    </p>
                    <button type="button" name="button" id="trigger-btn">Inhalt sortieren</button>
                </div>
            </div>
        </div>


    </div>
    <table class="table-style1">
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="underlined-table-row">
                <td class="horizontal-list-item">
                    <div class="picture-content-box">
                        <img src="picture3.jpg" alt="fresh ideas" />
                        <p class="name-link">
                            <a href="#">Rikki</a>
                        </p>
                    </div>

                </td>
                <td> Gernsbach</td>
            </tr>
            <tr class="underlined-table-row">
                <td>
                    <p class="name-link">
                        <a href="#">Abacus P</a>
                    </p>
                </td>
                <td> Cernsbach</td>
            </tr>
            <tr class="underlined-table-row">
                <td class="horizontal-list-item">
                    <div class="picture-content-box">
                        <img src="http://static.lolskill.net/img/skins/1215/rengar_0.jpg" alt="fresh ideas" />
                        <p class="name-link">
                            <a href="#">Solo</a>
                        </p>
                    </div>

                </td>
                <td> Gernsbach</td>
            </tr>
            <tr class="underlined-table-row">
                <td>
                    <p class="name-link">
                        <a href="#">Ben Afflect</a>
                    </p>
                </td>
                <td> Atu</td>
            </tr>
            <tr class="underlined-table-row">
                <td>
                    <p class="name-link">
                        <a href="#">Aladin</a>
                    </p>
                </td>
                <td> Boco</td>
            </tr>
        </tbody>
    </table>
